version: '3.8'

services:
  manager_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    env_file:
      - .env.development
    depends_on:
      - manager_database
    networks:
      - external_network

  manager_database:
    image: postgres:14
    environment:
      POSTGRES_DB: manager_db
      POSTGRES_USER: maurisc
      POSTGRES_PASSWORD: alegra_challenge
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - external_network

networks:
  external_network:
    external: true

volumes:
  postgres_data:
